"""empty message

Revision ID: 318240d24adb
Revises: d9dbd21b6ef5
Create Date: 2025-03-16 01:56:35.336322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318240d24adb'
down_revision = 'd9dbd21b6ef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
